[package]
name = "errorium"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
errorium-macro = { workspace = true }

[dev-dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
